# -*- coding: utf-8 -*-
"""FA-LAB4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i7zpgTmP7Tvg12mh5xWyfNzppfPW5DE8
"""

import pandas as pd
df = pd.read_csv("/content/anomaly_train.csv")
df.info()

import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder

lbl_enc = LabelEncoder()
df['Location'] = lbl_enc.fit_transform(df['Location'])
df['Type'] =lbl_enc.fit_transform(df['Type'])
df

x = df.drop('TransactionID',axis=1)

model = IsolationForest(n_estimators=100, contamination=0.1)
model.fit(x)
y_pred = model.predict(x)

df["anomaly_score"] = model.decision_function(x)

df['AnomalyType'] = ["Anomaly" if x<0 else "Normal" for x in df['anomaly_score']]

import seaborn as sns

anomalies = df.loc[df["anomaly_score"] < 0]

plt.scatter(df["TransactionID"], df["anomaly_score"])
plt.scatter(anomalies["TransactionID"], anomalies["anomaly_score"], color="r", label="Anomaly")
plt.xlabel("TransactionID")
plt.ylabel("anomaly_score")
plt.legend()
plt.show()

"""**This scatter plot above clearly shows the Transactions that are "Anomalies" out of all transactions in the dataset**"""